plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.usbserialtobluetoothbridge'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.usbserialtobluetoothbridge"
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (System.getenv("SIGNING_KEY_FILE")) {
                storeFile file(System.getenv("SIGNING_KEY_FILE"))
                storePassword System.getenv("KEY_STORE_PASSWORD")
                keyAlias System.getenv("ALIAS")
                keyPassword System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (System.getenv("SIGNING_KEY_FILE")) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.usb.serial
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}